services:
  - type: web
    name: missionaries-cannibals
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn missionaries_cannibals.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: missionaries_cannibals.settings
